print("Vítejte v kalkulačce")
print("Napište první číslo")
a = float(input())
print("Napište druhé číslo")
b = float(input())
print("Součet:",a+b)
print("Rozdíl:",a-b)
print("Součín:",a*b)
print("Podíl:",a/b)
print("Zbytek po dělení:",a%b)
print("Umocnění:",a**b)
